# _config.yml

url: "https://www.unveil2u.com"
baseurl: ""
port: 4002
permalink: pretty

title: Time-Space Photos - Your Best Memory Building and Sharing Tool
tagline: photos,memeory,memories,old time, time space,private,share,friends,families
description: Time-Space Photos is a powerful App to help you build old memories according to your photos. And, you can choose to share your stories with families and friends

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false

feed:
  path: /feed.xml

include:
  - quickdemo/dist/
  - quickdemo/*.md
  - quickdemo/**/data/

exclude:
  - quickdemo/**/node_modules/