/**
 * Reads pixel data from an image URL.
 * @param {string} imageUrl The URL of the 8-bit displacement map image.
 * @returns {Promise<Uint8ClampedArray>} A promise that resolves to the pixel data array (RGBA).
 */
function getPixelDataFromImage(imageUrl) {
  return new Promise<ImageDataArray>((resolve, reject) => {
    const img = new Image();
    // Set crossOrigin to use CORS if the image is on another domain
    img.crossOrigin = "Anonymous";

    img.onload = () => {
      // 1. Create a temporary canvas element
      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");

      // 2. Set canvas dimensions to match the image
      canvas.width = img.width;
      canvas.height = img.height;

      // 3. Draw the image onto the canvas
      ctx.drawImage(img, 0, 0);

      // 4. Get the pixel data for the entire image area
      // The data is a Uint8ClampedArray where every four elements are R, G, B, A for one pixel.
      const imageData = ctx.getImageData(0, 0, img.width, img.height);
      resolve(imageData.data);
    };

    img.onerror = (error) => {
      reject(
        new Error(`Failed to load image: ${imageUrl}. Check CORS settings.`)
      );
    };

    // Start loading the image
    img.src = imageUrl;
  });
}

// Example Usage:
async function processImage() {
  try {
    // Use the URL of your 8-bit image (can be a tile URL generated by QGIS)
    const pixelData = await getPixelDataFromImage(
      "/quickdemo/30days-map-challenge/gebco_bathy.5400x2700_8bit.jpg"
    );

    console.log(`Total pixels (RGBA values): ${pixelData.length}`);

    // Read the R value of the first pixel (top left corner)
    // For an 8-bit grayscale image, R, G, and B bands will typically hold the same value.
    const firstPixelRedValue = pixelData[0];
    const firstPixelGreenValue = pixelData[1];
    const firstPixelBlueValue = pixelData[3];

    console.log(`Pixel value at (0, 0) (Red band): ${firstPixelRedValue}`);
    console.log(`Pixel value at (0, 0) (Green band): ${firstPixelGreenValue}`);
    console.log(`Pixel value at (0, 0) (Green band): ${firstPixelBlueValue}`);
  } catch (error) {
    console.error(error);
  }
}

processImage();
// Run the function
// processImage();
